package org.zhou.forever.truegrave.mapper;

import java.util.List;
import org.zhou.forever.truegrave.domain.Permission;

public interface PermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Mon Oct 21 10:37:33 CST 2019
     */
    int deleteByPrimaryKey(Integer permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Mon Oct 21 10:37:33 CST 2019
     */
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Mon Oct 21 10:37:33 CST 2019
     */
    Permission selectByPrimaryKey(Integer permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Mon Oct 21 10:37:33 CST 2019
     */
    List<Permission> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbggenerated Mon Oct 21 10:37:33 CST 2019
     */
    int updateByPrimaryKey(Permission record);
}