package org.zhou.forever.truegrave.mapper;

import java.util.List;

import org.springframework.stereotype.Component;
import org.zhou.forever.truegrave.domain.Role;

@Component
public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Mon Oct 21 10:37:33 CST 2019
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Mon Oct 21 10:37:33 CST 2019
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Mon Oct 21 10:37:33 CST 2019
     */
    Role selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Mon Oct 21 10:37:33 CST 2019
     */
    List<Role> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Mon Oct 21 10:37:33 CST 2019
     */
    int updateByPrimaryKey(Role record);

    Role selectByName(String roleName);
}