package org.zhou.forever.truegrave.mapper;

import java.util.List;
import java.util.Set;

import org.springframework.stereotype.Component;
import org.zhou.forever.truegrave.domain.Role;
import org.zhou.forever.truegrave.domain.User;

@Component
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Oct 21 10:37:33 CST 2019
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Oct 21 10:37:33 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Oct 21 10:37:33 CST 2019
     */
    User selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Oct 21 10:37:33 CST 2019
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Oct 21 10:37:33 CST 2019
     */
    int updateByPrimaryKey(User record);

    /**
     * 根据用户名查找用户
     *
     * @param username
     * @return
     */
    User selectByName(String username);

    Set<String> selectRolesById(Integer userId);
}