package org.zhou.forever.truegrave.domain;

public class Permission extends BaseDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.permission_id
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    private Integer permissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.name
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.pid
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.parent_name
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    private String parentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.type
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.url
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.code
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.color
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.icon
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.sort
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    private Byte sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.permission_id
     *
     * @return the value of t_permission.permission_id
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.permission_id
     *
     * @param permissionId the value for t_permission.permission_id
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.name
     *
     * @return the value of t_permission.name
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.name
     *
     * @param name the value for t_permission.name
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.pid
     *
     * @return the value of t_permission.pid
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.pid
     *
     * @param pid the value for t_permission.pid
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.parent_name
     *
     * @return the value of t_permission.parent_name
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.parent_name
     *
     * @param parentName the value for t_permission.parent_name
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    public void setParentName(String parentName) {
        this.parentName = parentName == null ? null : parentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.type
     *
     * @return the value of t_permission.type
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.type
     *
     * @param type the value for t_permission.type
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.url
     *
     * @return the value of t_permission.url
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.url
     *
     * @param url the value for t_permission.url
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.code
     *
     * @return the value of t_permission.code
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.code
     *
     * @param code the value for t_permission.code
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.color
     *
     * @return the value of t_permission.color
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.color
     *
     * @param color the value for t_permission.color
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.icon
     *
     * @return the value of t_permission.icon
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.icon
     *
     * @param icon the value for t_permission.icon
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.sort
     *
     * @return the value of t_permission.sort
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    public Byte getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.sort
     *
     * @param sort the value for t_permission.sort
     *
     * @mbggenerated Mon Oct 21 01:24:44 CST 2019
     */
    public void setSort(Byte sort) {
        this.sort = sort;
    }
}